name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ensure-newline-at-eof:
    name: Ensure newline at end of file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run shell script
        run: bash ./scripts/ensure-newline-at-eof.sh

  eslint-prettier:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run shell script
        run: yarn lint

  rustfmt:
    runs-on: ubuntu-latest
    name: Check Rust code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run rustfmt
        run: cargo fmt -- --check
