name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@2.2.1
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Run shell script
        run: pnpm run lint
